version: 2
jobs:
  
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/employee-award-portal
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:10.15.0
        environment:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PORT: 3306
          IS_CI: true
          JWT_SECRET: d055859a-359a-49ea-8608-4339755a9290
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      
    working_directory: ~/employee-award-portal
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run api:test

  deploy-staging:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v circleci@$EAP_STAGING_HOST "./employee-award-portal/.circleci/deploy.sh"
      
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy-staging:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - test


